# Generated by Django 4.1 on 2022-10-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Post Updated Date')),
                ('like_count', models.PositiveIntegerField()),
                ('dislike_count', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post', verbose_name='Post likes and dislikes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
