# Generated by Django 4.1 on 2022-10-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='Post Title')),
                ('slug', models.SlugField(max_length=250, unique_for_date='published_date', verbose_name='Post Slug')),
                ('body', models.TextField(verbose_name='Post Body')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Post Published Date')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='published', max_length=9, verbose_name='Post Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Post Updated Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Post Author')),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
    ]
