# Generated by Django 4.1 on 2022-10-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Post Updated Date')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=250, unique_for_date='created_at', verbose_name='Category Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
